### ISSUE TITLE
可能需要檢查平面的坡度

### ISSUE THREAD

**Issue by xwc2021** [xwc2021/PlanetCamera#16]
現在的阿寶在上坡時有點緩慢，檢查坡度如果太陡就提高移動的加速度，應該可以解決。

**Comment by xwc2021** [comment]
super mario 3d world在平面和斜坡上行走和加速的速度是一樣的；另外mario在斜坡上還可以溜滑梯也。

**Comment by xwc2021** [comment]
還不能溜滑梯，不過現在在平面跟斜坡上走已經一樣快了

**Comment by xwc2021** [comment]
目前只抵消掉GravityAlongSlope，但是沒有考慮摩擦力。
在不同的坡度摩擦力其實是不同的，在坡度較大時，摩擦力也較小。
只抵消掉GravityAlongSlope，但坡度較大時因為摩擦力也變小，所以反而上升的速度更快了。

目前只用MaxForceLimit去限制力的大小，仍需要手動微調。

**Comment by xiangwei71** [comment]
avoidStickTool.alongSlopeOrGround(ref moveForce, planeNormal, gravityDir);
也會讓上升速度變快也
