### ISSUE TITLE
從其他地圖傳送到Donuts地圖時，camera就會跳掉

### ISSUE THREAD

**Issue by xwc2021** [xwc2021/PlanetCamera#27]

**Comment by xiangwei71** [comment]
當出生點離地面太近才會發生，目前還不知道是什麼原因

**Comment by xwc2021** [comment]
FixedUpdate不一定在第1個frame就執行
https://www.youtube.com/watch?v=egudW_Ucq7c

而目前計算camera的surface follow是使用groundUp和previousGroundUp來判定
doAdjustByGroundUp是在Update裡執行
如果第1個frame沒有執行到，那麼doAdjustByGroundUp呼叫
Vector3 groundUp = planetMovable.GroundUp;
抓到的groupUp會是(0,0,0)
